#ifndef PROJET_PLATEAU_H
#define PROJET_PLATEAU_H
#include "entitees/balle.h"

#define DOUBLEVERTICAL 186
#define DOUBLEHORIZONTAL 205
#define DOUBLEANGLEHAUTGAUCHE 201
#define DOUBLEANGLEHAUTDROIT 187
#define DOUBLEANGLEBASGAUCHE 200
#define DOUBLEANGLEBASDROITE 188
#define VERTICAL 179
#define HORIZONTAL 196
#define LINK 197


void afficherCase();


#endif
